services:
  postgres:
    image: postgres:16
    container_name: steamdb
    environment:
      POSTGRES_DB: steamdb
      POSTGRES_USER: hena
      POSTGRES_PASSWORD: hena
    ports:
      - "5432:5432"

  steambot:
    build: .
    container_name: steambot
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/steamdb
      SPRING_DATASOURCE_USERNAME: hena
      SPRING_DATASOURCE_PASSWORD: hena
    restart: unless-stopped
